### ISSUE TITLE
Server Crash - No Class Def Found

### ISSUE THREAD

**Issue by Trellinane** [Mrthomas20121/biolib#1]
Seems to be an issue with biolib.  It was added because of Tinkers Reforged 1.3.5 being present.  First tried 1.1.1 but then saw the note about it not being compatible with Tinker's Reforged yet tried rolling back to 1.0.1 with same result.

[pastebin](https://pastebin.com/03wa7qVi)

**Comment by Mrthomas20121** [comment]
you need bio lib 1.0.7 to work with the latest tinkers reforged release. you can expect a tinkers reforged update soon(this week).
